name: Prepare
description: Prepares the repo for a typical CI job

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - run: |
        npm i string-strip-html
        npm install
      shell: bash
